import bcrypt from 'bcryptjs'
const data ={
    users:[
        {
            name:'admin',
            email:'admin@gmail.com',
            password:bcrypt.hashSync('admin'),
            isAdmin:true,
        },
        {
            name:'saif',
            email:'saif@gmail.com',
            password:bcrypt.hashSync('saif'),
            isAdmin:false,
        }
    ],
    products:[
        {
            name:"Free Shirt",
            slug:"free-Shirt",
            category:"Shirts",
            image:"/images/shirt1.jpg",
            price:70,
            brand:'Nike',
            rating:4.5,
            numReviews:8,
            countInStock:20,
            description:"A Popular Shirt",
        },
        {
            name:"Fit Shirt",
            slug:"fit-Shirt",
            category:"Shirts",
            image:"/images/shirt2.jpg",
            price:80,
            brand:'Easy',
            rating:3.5,
            numReviews:10,
            countInStock:20,
            description:"A Popular Shirt",
        },
        {
            name:"Slim Shirt",
            slug:"slim-Shirt",
            category:"Shirts",
            image:"/images/shirt3.jpg",
            price:90,
            brand:'Raymond',
            rating:4.5,
            numReviews:5,
            countInStock:20,
            description:"A Popular Shirt",
        },
        {
            name:"Golf Pants",
            slug:"golf-pants",
            category:"Pants",
            image:"/images/pants1.jpg",
            price:90,
            brand:'Oliver',
            rating:2.5,
            numReviews:13,
            countInStock:20,
            description:"A Popular Pants",
        },
        {
            name:"Fit Pants",
            slug:"fit-pants",
            category:"Pants",
            image:"/images/pants2.jpg",
            price:90,
            brand:'Zara',
            rating:2.5,
            numReviews:13,
            countInStock:20,
            description:"A Popular Pants",
        },
        {
            name:"Classic Pants",
            slug:"classic-pants",
            category:"Pants",
            image:"/images/pants3.jpg",
            price:70,
            brand:'Casely',
            rating:2.5,
            numReviews:14,
            countInStock:20,
            description:"A Popular Pants",
        },
    ]
};
export default data;